### PR TITLE
Updating requirements

### PR DESCRIPTION
**Pull request by annagellerbring**
This PR adds/fixes text in requirements.

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.sclifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] click on Provkrav

**Expected test outcome**:
- [x] check that the text is fine
- [x] Take a screenshot and attach or copy/paste the output.

Screen Shot 2020-10-27 at 14 20 30

**Review:**
- [x] code approved by EM
- [x] tests executed by EM
- [x] "Merge and deploy" approved by EM
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by annagellerbring** [comment]
@elevu please edit the info for the PR if needed. Didn't know what to fill in for the testing etc.

**Review by elevu — APPROVED** [review]
Approved! I can merge and deploy if you don't have any more changes to add

**Comment by annagellerbring** [comment]
> Approved! I can merge and deploy if you don't have any more changes to add

Thanks! No please deploy, this was it for this time.

**Comment by elevu** [comment]
Deployed!

**Pull request merged**
