### PR TITLE
Updating sample requirements for FFPE

### PR DESCRIPTION
**Pull request by annagellerbring**
This PR adds information on how we handle low qualitative FFPE samples in Panel/Exome sequencing.

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.sclifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [ ] login on https://clinical-stage.scilifelab.se/
- [ ] click on https://github.com/Clinical-Genomics/cgweb/tree/updating-sample-requirements-for-FFPE, see updates for sample requirements Exome-and panel sequencing both swedish and english version. 

**Expected test outcome**:
- [ ] see commits
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @vwirta 
- [ ] tests executed by N/A
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by vwirta** [comment]
@barrystokman can you help us with this one as well? What do you think, does this need to be tested? Only text edits...

**Comment by annagellerbring** [comment]
I realised that the words I wanted to be bold, maybe they needed to asterisks on each side instead of one.

**Comment by barrystokman** [comment]
@vwirta @annagellerbring Maybe a quick test to see if the text is really bolded? :)

I'll have a look

**Comment by barrystokman** [comment]
@vwirta @annagellerbring I can't login to https://clinical-stage.scilifelab.se/, it's the recurring problem with google authentication again. I can't solve that. I've tried clearing cache, another browser, nothing works...

Let's just deploy...

**Comment by barrystokman** [comment]
Deployed:
image


image
image

**Comment by annagellerbring** [comment]
@barrystokman thank you!

**Pull request merged**
