### PR TITLE
Require tumour for balsamic case

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds validation to the Orderportal that each balsamic case has at least on tumour sample. It also checks that tumour purity can be specified only when the sample is from tumour

**How to prepare for test**:
- [x] ssh to clinical-db or ask PG to install branch
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.sclifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

1) **How to test tumour requirement for balsamic case without tumour**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] create an balsamic order with a case without tumour samples 

**Expected test outcome**:
- [x] check that you can't save the samples 

2) **How to test tumour requirement for balsamic case with tumour**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] create an balsamic order with a case with tumour sample

**Expected test outcome**:
- [x] check that you can save the samples 

3) **How to test tumour purity requirement for balsamic case without tumour**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] create an balsamic order with a case without tumour samples but with tumour purity

**Expected test outcome**:
- [x] check that you can't save the samples 

4) **How to test tumour purity requirement for balsamic case with tumour**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] create an balsamic order with a case with tumour samples but with tumour purity

**Expected test outcome**:
- [x] check that you can save the samples 

- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by APJ
- [x] tests executed by KE
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@keyvanelhami would you like to test and review the code of this PR?

**Comment by keyvanelhami** [comment]
The order went through even when no tumor was selected. The step 1 test didn't pass
Screen Shot 2020-05-28 at 8 28 06 AM

**Comment by keyvanelhami** [comment]
Test 1 passed:
Screen Shot 2020-05-28 at 9 36 53 AM

Test 2 passed:
Screen Shot 2020-05-28 at 9 40 36 AM

Test 3 passed:
Screen Shot 2020-05-28 at 10 00 23 AM


Test 4 passed:
Screen Shot 2020-05-28 at 9 45 20 AM
Screen Shot 2020-05-28 at 9 45 11 AM

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Comment by patrikgrenfeldt** [comment]
Thank you @keyvanelhami and @ashwini06 for your help!

**Pull request merged**
