### PR TITLE
Added information regarding closed envelopes

### PR DESCRIPTION
**Pull request by vwirta**
This PR adds/fixes the missing information about closed envelopes. Ref to DEV Prod#124 

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] navigate to Beställningar
- [x] read new text
- [x] Take a screenshot and attach or copy/paste the output.

**Expected test outcome**:
- [x] check that the text is updated

**Review:**
- [x] code approved by @patrikgrenfeldt 
- [x] tests executed by @b4ckm4n
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by annaengstrom** [comment]
I edited the template above as PROD#124 was linked to the wrong Github issue.

**Comment by annaengstrom** [comment]
I cannot check the new update for .vue files. Either someone from Bioinfo/IT can do it or @patrikgrenfeldt or @henrikstranneheim can help me to view on stage, I need it also for other PR Github.

**Comment by annaengstrom** [comment]
Let deploy this anyway, @patrikgrenfeldt can you do that?

**Comment by patrikgrenfeldt** [comment]
> Let deploy this anyway, @patrikgrenfeldt can you do that?

Sure, nicely done @annaengstrom, @annagellerbring and @b4ckm4n!

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Pull request merged**
