### PR TITLE
Update requirements with FFPE information and extraction system for Microbial samples

### PR DESCRIPTION
**Pull request by annaengstrom**
This PR adds information that FFPE not allowed for human WGS

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] click on https://clinical-stage.scilifelab.se/requirements

**Expected test outcome**:
- [x] check that information about FFPE is added and that CG should be contacted before order for MagNA pure 96 and maelstrom extraction systems have been used
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @b4ckm4n 
- [x] tests executed by @b4ckm4n 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by annaengstrom** [comment]
@patrikgrenfeldt can you deploy please?

**Comment by patrikgrenfeldt** [comment]
@annaengstrom could we make sure this PR is verified/validated (see bellow piture)?
image
The 3 review checkboxes should be checked and the sign of the responsible on the same line. "This version is a" section should have one check to indicate if it should verified or validaten, as well as how it should be version-bumped before deploying.

**Comment by annaengstrom** [comment]
@b4ckm4n could you please fill out the template above

 code approved by
 tests executed by

**Comment by patrikgrenfeldt** [comment]
deployed on clinical-db:
image

**Pull request merged**
