### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by annagellerbring**
updated requirements for different number of samples

### CODE REVIEW

**Comment by barrystokman** [comment]
What needs to be done to finish this? Just push it to prod? Review of any kind?

**Comment by annagellerbring** [comment]
@patrikgrenfeldt just push it to prod? or do you usually read my changes?

**Comment by patrikgrenfeldt** [comment]
@annagellerbring, Deployed now, sorry it took so long time. 

@barrystokman, What I usually do with changes from the Lab-team is to deploy it to stage and make sure that we didn't accidentally loose any obvious parts of the layout and then deploy it to prod (including bump)

**Comment by ingkebil** [comment]
@patrikgrenfeldt maybe good to describe this in either the README.md or PR template of cgweb. Can you take care of that?

**Comment by patrikgrenfeldt** [comment]
Sure

**Pull request merged**
