### PR TITLE
Create PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR fixes some challenges in using the current PR-template

**How to test**:
- [x] Read the PR-template

**Expected test outcome**:
- [x] check that it makes sense and feels good
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @henrikstranneheim 
- [x] tests executed by @patrikgrenfeldt 
- [x] "Merge and deploy" approved by @patrikgrenfeldt 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by annaengstrom** [comment]
Just to make sure I understand, there was no PR template in this repo before, right?

I don't understand the "test" phase, can you please explain?

**Comment by henrikstranneheim** [comment]
That is where you fill in how to "test" your changes e.g. viewing the pages you have changed that they actually are changed. You can look at the cg PR number 542 if you want a real example

**Comment by henrikstranneheim** [comment]
@annaengstrom Yes, you are right. We are creating one so that you can describe the changes you have made and test them and then in the future with the right docs and minor/patch "merge and deploy".

**Comment by patrikgrenfeldt** [comment]
Test result:
image

👍

**Pull request merged**
