### PR TITLE
Update orders.vue

### PR DESCRIPTION
**Pull request by annaengstrom**
This PR adds/fixes sample submission time, and added link to English section of page.

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] click on link Beställningar in upper bar
- [x] check sample submission time in both English and Swedish
- [x] click "For English version, click _here_." at top of page

**Expected test outcome**:
- [x] sample submission time is 8-15
- [x] English version link works.
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @hassanfa 
- [x] tests executed by @b4ckm4n 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by annaengstrom** [comment]
@patrikgrenfeldt next step for this?

**Comment by annaengstrom** [comment]
@patrikgrenfeldt can you deploy please?

**Comment by patrikgrenfeldt** [comment]
> @patrikgrenfeldt can you deploy please?

Sure, nice work!

**Comment by patrikgrenfeldt** [comment]
Deployed on clinical-db:
image

**Pull request merged**
