### PR TITLE
Support for OF 1605.7 and 1603.9

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds support for OF 1605.7 and 1603.9

**How to setup test**:
1. install on stage of the clinical-db machine: `bash servers/resources/clinical-db.scilifelab.se/update-cgweb-stage.sh remove-other-elution-buffer`
1. install on stage of the clinical-db machine: `bash servers/resources/clinical-db.scilifelab.se/update-clinical-api-stage.sh metagenome-OF-1605-7`

HOW TO TEST **submit Microbial order**:
1. login to OP
1. create and submit Microbial order with OF 1603.9 

**Expected outcome**:
- [x] Order should be accepted by OP (TN 191002)

HOW TO TEST **submit Metagenome order**:
1. login to OP
1. create and submit Microbial Metagenome order with OF 1605.7

**Expected outcome**:
- [x] Order should be accepted by OP (TN 191002)

HOW TO TEST **elution buffer "other"**:
1. login to OP
1. create and submit Microbial/Metagenome order
1. select option "Other ..." in the Elution buffer select
1. Press save

**Expected outcome**:
Microbial order: (TN 191002)
- [x] comment should be surrounded by a red rectangle
- [x] entering a comment and pressing save should resolve the requirement on comment

Metagenome order: (TN 191002)
- [x] comment should be surrounded by a red rectangle
- [x] entering a comment and pressing save should resolve the requirement on comment

Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] AM 1603.9 approved by @AnnaLeinfelt 
- [x] AM 1605.7 approved by @AnnaLeinfelt 
- [x] cgweb code approved by @ingkebil
- [x] [cg](https://github.com/Clinical-Genomics/cg/pull/440) code approved by @ingkebil 
- [x] tests executed by @talnor 
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because we add functionality in a backwards compatible manner

### CODE REVIEW

**Comment by talnor** [comment]
"Comment" surrounded with red rectangle before text entered. Results for 1605:7 and 1603:9 respectively below.
Screen Shot 2019-10-02 at 2 26 07 PM
Screen Shot 2019-10-02 at 2 25 45 PM
Screen Shot 2019-10-02 at 2 24 25 PM
Screen Shot 2019-10-02 at 2 22 55 PM

**Comment by annaengstrom** [comment]
Just a comment on approval of AM docs, this can only be done by AL and VW but they are not part of the review?

**Comment by vwirta** [comment]
@annaengstrom correct, if there is a document that needs to be approved, tag me either here or send to me in AMS and I will take care of it.

**Comment by patrikgrenfeldt** [comment]
deployed

**Pull request merged**
